export interface Skill {
  id: string;
  name: string;
  category: 'Development' | 'Design' | 'Content' | 'Marketing' | 'Infrastructure' | 'Reasoning' | 'Utilities';
  icon: string;
  description: string;
  trigger: string;
  instructions: string[];
  constraints: string[];
  status: 'active' | 'beta' | 'placeholder';
}

export const SKILL_CATEGORIES = [
  'Development',
  'Design',
  'Content',
  'Marketing',
  'Infrastructure',
  'Reasoning',
  'Utilities',
] as const;

export const skills: Skill[] = [
  {
    id: 'superpowers',
    name: 'Superpowers',
    category: 'Development',
    icon: 'Zap',
    description: 'Enhanced coding capabilities with multi-file awareness, architecture patterns, and best practices.',
    trigger: 'code, build, implement, create component',
    instructions: ['Analyze requirements', 'Plan architecture', 'Generate working code', 'Test edge cases'],
    constraints: ['No pseudocode', 'Must compile', 'Follow existing patterns'],
    status: 'active',
  },
  {
    id: 'mcp-builder',
    name: 'MCP Builder',
    category: 'Development',
    icon: 'Server',
    description: 'Build and configure Model Context Protocol servers for tool integration.',
    trigger: 'mcp, server, tool integration, api endpoint',
    instructions: ['Define MCP schema', 'Implement tools', 'Add error handling', 'Write tests'],
    constraints: ['Must follow MCP spec', 'Include TypeScript types', 'Document all tools'],
    status: 'active',
  },
  {
    id: 'nvidia-build',
    name: 'NVIDIA Build',
    category: 'Development',
    icon: 'Cpu',
    description: 'NVIDIA-specific integrations including NIM APIs, CUDA, and GPU-optimized workflows.',
    trigger: 'nvidia, nim, gpu, cuda',
    instructions: ['Configure NVIDIA endpoints', 'Optimize for GPU inference', 'Implement streaming'],
    constraints: ['Use official SDKs', 'Handle rate limits', 'Implement backoff'],
    status: 'active',
  },
  {
    id: 'explained-code',
    name: 'Explained Code',
    category: 'Development',
    icon: 'BookOpen',
    description: 'Break down complex code into clear, annotated explanations with visual diagrams.',
    trigger: 'explain, how does, walkthrough, annotate',
    instructions: ['Read target code', 'Identify key patterns', 'Create annotations', 'Generate diagrams'],
    constraints: ['Beginner-friendly language', 'Show data flow', 'Include edge cases'],
    status: 'active',
  },
  {
    id: 'frontend-design',
    name: 'Frontend Design',
    category: 'Design',
    icon: 'Palette',
    description: 'Design and implement production-ready UI components with accessibility and responsive design.',
    trigger: 'design, ui, component, layout',
    instructions: ['Analyze design requirements', 'Choose component architecture', 'Implement with animations', 'Test responsiveness'],
    constraints: ['Semantic HTML', 'WCAG 2.1 AA', 'Mobile-first', 'No layout shifts'],
    status: 'active',
  },
  {
    id: 'web-design-guidelines',
    name: 'Web Design Guidelines',
    category: 'Design',
    icon: 'Ruler',
    description: 'Apply design system tokens, spacing rules, color theory, and typography best practices.',
    trigger: 'design system, tokens, spacing, typography',
    instructions: ['Audit current design', 'Define design tokens', 'Apply guidelines', 'Document decisions'],
    constraints: ['Consistent spacing scale', 'Accessible color ratios', 'System font stack'],
    status: 'active',
  },
  {
    id: 'web-artifacts-builder',
    name: 'Web Artifacts Builder',
    category: 'Design',
    icon: 'Globe',
    description: 'Build standalone HTML/CSS/JS artifacts — landing pages, interactive widgets, demos.',
    trigger: 'landing page, demo, artifact, widget',
    instructions: ['Scope artifact', 'Design layout', 'Build HTML/CSS/JS', 'Package as standalone file'],
    constraints: ['Self-contained', 'No build step', 'Works offline', 'Under 100KB'],
    status: 'active',
  },
  {
    id: 'photography-ai',
    name: 'Photography AI',
    category: 'Design',
    icon: 'Camera',
    description: 'Generate, analyze, and enhance images using AI vision models and generation APIs.',
    trigger: 'image, photo, generate picture, visual',
    instructions: ['Understand visual requirements', 'Craft prompts', 'Generate images', 'Post-process'],
    constraints: ['High resolution', 'Consistent style', 'No artifacts'],
    status: 'active',
  },
  {
    id: 'seo-content-writer',
    name: 'SEO Content Writer',
    category: 'Content',
    icon: 'FileText',
    description: 'Create SEO-optimized content with keyword research, meta tags, and structured data.',
    trigger: 'seo, blog post, article, content',
    instructions: ['Research keywords', 'Outline content', 'Write optimized copy', 'Add meta data'],
    constraints: ['Primary keyword in title', 'Natural keyword density', 'Internal linking'],
    status: 'active',
  },
  {
    id: 'humanizer',
    name: 'Humanizer',
    category: 'Content',
    icon: 'User',
    description: 'Transform AI-generated text into natural, human-sounding content while preserving meaning.',
    trigger: 'humanize, natural, rewrite, tone',
    instructions: ['Analyze source text', 'Identify AI patterns', 'Rewrite naturally', 'Verify meaning preserved'],
    constraints: ['No loss of information', 'Varied sentence length', 'Natural transitions'],
    status: 'active',
  },
  {
    id: 'social-content-pillars',
    name: 'Social Content Pillars',
    category: 'Content',
    icon: 'Share2',
    description: 'Define and generate content pillars for social media strategy.',
    trigger: 'content pillar, social strategy, brand voice',
    instructions: ['Identify brand values', 'Define pillars', 'Create content calendar', 'Generate templates'],
    constraints: ['Consistent brand voice', 'Platform-specific formats', 'Engaging hooks'],
    status: 'active',
  },
  {
    id: 'social-media-manager',
    name: 'Social Media Manager',
    category: 'Content',
    icon: 'Megaphone',
    description: 'Plan, create, and schedule social media content across platforms.',
    trigger: 'social media, schedule, post, campaign',
    instructions: ['Plan content calendar', 'Create posts', 'Schedule publishing', 'Track engagement'],
    constraints: ['Platform guidelines', 'Optimal posting times', 'Hashtag strategy'],
    status: 'active',
  },
  {
    id: 'gumroad-pipeline',
    name: 'Gumroad Pipeline',
    category: 'Marketing',
    icon: 'ShoppingCart',
    description: 'End-to-end product pipeline for Gumroad — from ideation to launch and sales optimization.',
    trigger: 'gumroad, product launch, sell, monetize',
    instructions: ['Validate product idea', 'Create listing', 'Set pricing', 'Launch and promote'],
    constraints: ['Compelling copy', 'Clear value proposition', 'Social proof', 'Urgency elements'],
    status: 'active',
  },
  {
    id: 'jtbd-research',
    name: 'JTBD Research',
    category: 'Marketing',
    icon: 'Search',
    description: 'Jobs To Be Done framework research — understand customer needs and motivations.',
    trigger: 'research, customer needs, jtbd, user interview',
    instructions: ['Define research scope', 'Identify jobs', 'Map pain points', 'Prioritize opportunities'],
    constraints: ['Customer-first language', 'Actionable insights', 'Data-backed conclusions'],
    status: 'active',
  },
  {
    id: 'deployment-manager',
    name: 'Deployment Manager',
    category: 'Infrastructure',
    icon: 'Rocket',
    description: 'Manage deployments to Vercel, GitHub Pages, AWS, and other platforms.',
    trigger: 'deploy, vercel, github pages, production',
    instructions: ['Validate build', 'Configure environment', 'Deploy', 'Verify and monitor'],
    constraints: ['Zero-downtime', 'Environment variables secured', 'Rollback plan'],
    status: 'active',
  },
  {
    id: 'audit-analyzer',
    name: 'Audit Analyzer',
    category: 'Infrastructure',
    icon: 'Shield',
    description: 'Performance, accessibility, and security audits with actionable recommendations.',
    trigger: 'audit, performance, accessibility, security check',
    instructions: ['Run Lighthouse audit', 'Analyze results', 'Prioritize fixes', 'Generate report'],
    constraints: ['Score > 90 target', 'WCAG 2.1 AA compliance', 'No critical vulnerabilities'],
    status: 'active',
  },
  {
    id: 'chain-of-thought',
    name: 'Chain of Thought',
    category: 'Reasoning',
    icon: 'Brain',
    description: 'Structured step-by-step reasoning for complex problem decomposition and analysis.',
    trigger: 'think step by step, analyze, reason, break down',
    instructions: ['Define problem', 'Decompose into steps', 'Solve each step', 'Verify solution'],
    constraints: ['Show all work', 'Number each step', 'Verify at each stage'],
    status: 'active',
  },
  {
    id: 'socratic-method',
    name: 'Socratic Method',
    category: 'Reasoning',
    icon: 'HelpCircle',
    description: 'Ask probing questions to deepen understanding and challenge assumptions.',
    trigger: 'question, probe, challenge assumption, clarify',
    instructions: ['Identify claim', 'Question assumptions', 'Explore implications', 'Synthesize insights'],
    constraints: ['Open-ended questions', 'No leading questions', 'Build on answers'],
    status: 'active',
  },
  {
    id: 'devils-advocate',
    name: 'Devil\'s Advocate',
    category: 'Reasoning',
    icon: 'AlertTriangle',
    description: 'Stress-test ideas by finding counterarguments, edge cases, and failure modes.',
    trigger: 'counter, edge case, what if, stress test',
    instructions: ['Accept premise', 'Find counterarguments', 'Identify risks', 'Rate severity'],
    constraints: ['Constructive criticism', 'Specific examples', 'Actionable mitigation'],
    status: 'active',
  },
  {
    id: 'context-compressor',
    name: 'Context Compressor',
    category: 'Reasoning',
    icon: 'Minimize2',
    description: 'Compress and summarize context for efficient token usage in long conversations.',
    trigger: 'summarize, compress, condense, brief',
    instructions: ['Analyze full context', 'Extract key points', 'Compress preserving intent', 'Validate completeness'],
    constraints: ['No information loss', 'Preserve decisions', 'Keep action items'],
    status: 'active',
  },
  {
    id: 'output-formatter',
    name: 'Output Formatter',
    category: 'Utilities',
    icon: 'FileOutput',
    description: 'Format AI output into structured documents — Markdown, HTML, JSON, PDF-ready.',
    trigger: 'format, export, document, template',
    instructions: ['Analyze content', 'Select format', 'Apply template', 'Validate output'],
    constraints: ['Consistent formatting', 'Valid syntax', 'Print-ready'],
    status: 'active',
  },
  {
    id: 'skill-finder',
    name: 'Skill Finder',
    category: 'Utilities',
    icon: 'Compass',
    description: 'Discover and recommend the right skill for any task from the skills library.',
    trigger: 'which skill, find skill, recommend tool, best approach',
    instructions: ['Analyze task', 'Match to skills', 'Rank by relevance', 'Recommend with rationale'],
    constraints: ['Consider combinations', 'Explain trade-offs', 'Prefer simpler solutions'],
    status: 'active',
  },
  {
    id: 'simulation-sandbox',
    name: 'Simulation Sandbox',
    category: 'Utilities',
    icon: 'Box',
    description: 'Run scenario simulations, what-if analyses, and decision trees in a safe environment.',
    trigger: 'simulate, what if, scenario, model',
    instructions: ['Define scenario', 'Set parameters', 'Run simulation', 'Analyze outcomes'],
    constraints: ['Bounded scope', 'Clear assumptions', 'Quantified results'],
    status: 'active',
  },
  {
    id: 'web-reader',
    name: 'Web Reader',
    category: 'Utilities',
    icon: 'Globe',
    description: 'Extract and analyze content from web pages — articles, docs, and resources.',
    trigger: 'read url, fetch page, scrape, extract content',
    instructions: ['Fetch URL', 'Extract content', 'Parse structure', 'Return clean text'],
    constraints: ['Respect robots.txt', 'Handle errors gracefully', 'Cache results'],
    status: 'active',
  },
  {
    id: 'browser-use',
    name: 'Browser Use',
    category: 'Utilities',
    icon: 'Monitor',
    description: 'Automated browser interactions — navigation, form filling, screenshots, and testing.',
    trigger: 'browse, automate browser, screenshot, test page',
    instructions: ['Open page', 'Interact with elements', 'Capture results', 'Report findings'],
    constraints: ['Headless mode', 'Timeout handling', 'Clean up resources'],
    status: 'active',
  },
];

export function getSkillsByCategory(category: string): Skill[] {
  return skills.filter((s) => s.category === category);
}

export function getSkillById(id: string): Skill | undefined {
  return skills.find((s) => s.id === id);
}

export function searchSkills(query: string): Skill[] {
  const q = query.toLowerCase();
  return skills.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.trigger.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q)
  );
}
